---
data:
    name: "{{__sanitized_project_name__}}"
    title: "{{ project_title }}"
    description: "{{ description }}"
    keywords: ["{{ processed_keyword }}"] ## Processed data keyword to make this dataset reachable for other projects/benchmark components.
script: "src/{{__sanitized_project_name__}}.R" ## Change this to .py if you are using a py script
inputs:
    keywords: [" "] ## Input dataset keyword(s) to import. 
    files: [" "] ## Input file type(s). Should correspond to next section, e.g. "input_file1"
    prefix:
        ## File patterns to use for automatic detection. 
        ## Example: 
        # input_file1: "_INPUT1_"
        # input_file2: "_INPUT2_"
        # ...
outputs:
    template: "data/${name}/${name}_${out_name}.${out_end}" ## Automatic. To change if you want specific output names. 
    files:
        ## File patterns to use for automatic detection. 
        ## Example:
        # data_file1: 
        #     end: "FILE1_END"
        # data_file2:
        #     end: "FILE2_END"
        # ...
benchmark_name: "{{ benchmark_name }}" ## Name of the omnibenchmark to link this project with.
